[package]
name = "sp-ark-bls12-381"
version = "0.4.0-alpha"
authors = ["Parity Technologies <admin@parity.io>", "Achim Schneider <achim@parity.io>", "arkworks contributors" ]
description = "The BLS12-381 pairing-friendly elliptic curve, optimized for Substrate"
homepage = "https://arkworks.rs"
repository = "https://github.com/paritytech/ark-substrate"
documentation = "https://docs.rs/ark-bls12-381/"
keywords = ["cryptography", "finite-fields", "elliptic-curves", "substrate" ]
categories = ["cryptography"]
include = ["Cargo.toml", "src", "README.md", "LICENSE-APACHE", "LICENSE-MIT"]
license = "MIT/Apache-2.0"
edition = "2021"

[dependencies]
ark-ff = { git = "https://github.com/arkworks-rs/algebra", branch = "releases", default-features = false }
ark-std = { version = "0.4.0-alpha", default-features = false }
ark-serialize = { git = "https://github.com/arkworks-rs/algebra", branch = "releases", default-features = false }
ark-bls12-381 = { git = "https://github.com/arkworks-rs/curves", default-features = false }
ark-models = { path = "../../models", default-features = false }
sp-ark-utils = { path = "../utils", default-features = false  }

[dev-dependencies] 
ark-algebra-test-templates = { git = "https://github.com/arkworks-rs/algebra", branch = "releases", default-features = false }
sp-io =  { version = "7.0.0", git = "https://github.com/paritytech/substrate.git", default-features = false, branch = "achimcc/arkworks-integration" }
ark-ec = { git = "https://github.com/arkworks-rs/algebra", branch = "releases", default-features = false }
hex = "^0.4.0"

[features]
default = [ "curve" ]
std = [ 
    "ark-ff/std", 
    "ark-std/std", 
    "ark-serialize/std",
    "ark-bls12-381/std",
    "ark-models/std", 
    "sp-ark-utils/std",
    "ark-algebra-test-templates/std",
    "ark-ec/std",
    "sp-io/std"
]

curve = [ "scalar_field" ]
scalar_field = []

