[package]
name = "sp-ark-bw6-761"
version = "0.4.0-alpha.1"
authors = ["Parity Technologies <admin@parity.io>", "Achim Schneider <achim@parity.io>", "arkworks contributors" ]
repository = "https://github.com/paritytech/ark-substrate"
description = "The BW6-761 pairing-friendly elliptic curve, optimized for Substrate"
keywords = ["cryptography", "finite-fields", "elliptic-curves", "substrate" ]
categories = ["cryptography"]
include = ["Cargo.toml", "src", "README.md", "LICENSE-APACHE", "LICENSE-MIT"]
license = "MIT/Apache-2.0"
edition = "2021"

[dependencies]
ark-ff = { version="0.4.0-alpha", default-features = false }
ark-std = { version = "0.4.0-alpha", default-features = false }
ark-bw6-761 = { git = "https://github.com/arkworks-rs/curves", default-features = false }
ark-serialize = { git = "https://github.com/arkworks-rs/algebra", branch = "releases", default-features = false }
ark-models = { path = "../../models", default-features = false }
sp-ark-utils = { path = "../utils", default-features = false  }

[dev-dependencies]
ark-algebra-test-templates = { git = "https://github.com/arkworks-rs/algebra", branch = "releases", default-features = false }
ark-ec = { git = "https://github.com/arkworks-rs/algebra", branch = "releases", default-features = false }
sp-io =  { version = "7.0.0", git = "https://github.com/paritytech/substrate.git", branch = "achimcc/arkworks-integration", default-features = false }

[features]
default = []
std = [ 
    "ark-ff/std", 
    "ark-std/std", 
    "ark-bw6-761/std",
    "ark-serialize/std", 
    "ark-models/std",
    "sp-ark-utils/std",
    "ark-algebra-test-templates/std",
    "ark-ec/std", 
    "sp-io/std",
]

