name: Run benchmarks and publish to Github

on:
  push:
    branches:    
      - '*'
  pull_request:
    branches: 

  workflow_dispatch:

jobs:   
  rustfmt:
    runs-on: 'ubuntu-latest'
    steps:
      - name: Install Rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
          target: wasm32-unknown-unknown   

      - name: Install protoc
        uses: taiki-e/install-action@v1
        with:
          tool: protoc

      - name: checkout repo
        uses: actions/checkout@v2
        with:
          ref: main
          path: main

      - name: checkout arkworks examples for benchmarking
        uses: actions/checkout@master
        with:
          name: achimcc/substrate-arkworks-examples
          ref: refs/heads/release  
      
      - name: ls
        run: ls -la

      - name: Build benchmarks for main branch
        run: |
          cargo build --package node-template  \
          --profile release \
          --features runtime-benchmarks

      - name: Run benchmarks for main branch
        run: |
          ./target/release/node-template benchmark pallet \
              --chain dev \
              --execution=wasm \
              --wasm-execution=compiled \
              --pallet pallet-template \
              --extrinsic "*" \
              --steps 50 \
              --repeat 20 \
              --json \
              > results.json

      - name: Use current PR branch for benchmarking
        run: sed -i 's/replace-with-pr-branch/${{ github.ref_name }}/g' Cargo.toml

     - name: Build benchmarks for PR branch
        run: |
          cargo build --package node-template  \
          --profile release \
          --features runtime-benchmarks

      - name: Run benchmarks for PR branch
        run: |
          ./target/release/node-template benchmark pallet \
              --chain dev \
              --execution=wasm \
              --wasm-execution=compiled \
              --pallet pallet-template \
              --extrinsic "*" \
              --steps 50 \
              --repeat 20 \
              --json \
              > results.json

      - name: Compare benchmark result
        uses: openpgpjs/github-action-pull-request-benchmark@v1
        with:
          name: 'Time benchmark'
          tool: 'benchmarkjs'
          pr-benchmark-file-path: pr/examples/benchmarks.txt
          base-benchmark-file-path: master/examples/benchmarks.txt
          comment-on-alert: true
          alert-threshold: '130%'
          fail-on-alert: true
          fail-threshold: '150%'
          github-token: ${{ secrets.GITHUB_TOKEN }}
  
         