name: Run benchmarks

on:
  push:
    branches:    
      - '*'
  pull_request:
    branches: 

  workflow_dispatch:

jobs:   
  benchmark:
    runs-on: ubuntu-latest
    steps:
      - name: Install Rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
          target: wasm32-unknown-unknown
      - name: Install protoc
        uses: taiki-e/install-action@v1
        with:
          tool: protoc
      - name: clone substrate-arkworks-examples for benchmarking
        run: git clone https://github.com/achimcc/substrate-arkworks-examples
      - name: ls
        run: cd /home/runner/work && ls -la
      - name: Build benchmarks for main branch
        run: |
          cd substrate-arkworks-examples && \
          cargo build --package node-template  \
          --profile release \
          --features runtime-benchmarks
      - name: Run benchmarks for main branch
        run: |
          cd substrate-arkworks-examples && \
          ./target/release/node-template benchmark pallet \
              --chain dev \
              --execution=wasm \
              --wasm-execution=compiled \
              --pallet pallet-template \
              --extrinsic "*" \
              --steps 50 \
              --repeat 20 \
              --json \
              > ../results-main.json
      - name: clone repo
        run: git clone https://github.com/paritytech/ark-substrate
      - name: Get patched Cargo.toml
        run: cp ark-substrate/benchmarking/Cargo.toml substrate-arkworks-examples/Cargo.toml
      - name: Use current PR branch for benchmarking
        run: sed -i 's/replace-with-pr-branch/${{ github.ref_name }}/g' substrate-arkworks-examples/Cargo.toml
      - name: Build benchmarks for PR branch
        run: |
         cd substrate-arkworks-examples && \
          cargo build --package node-template  \
          --profile release \
          --features runtime-benchmarks
      - name: Run benchmarks for PR branch
        run: |
          cd substrate-arkworks-examples && \
          ./target/release/node-template benchmark pallet \
              --chain dev \
              --execution=wasm \
              --wasm-execution=compiled \
              --pallet pallet-template \
              --extrinsic "*" \
              --steps 50 \
              --repeat 20 \
              --json \
              > ../results-pr.json
      - name: Store benchmark result
        uses: benchmark-action/github-action-benchmark@v1
        with:
          tool: cargo
          output-file-path: ./results-main.json
          external-data-json-path: ./results-pr.json
          fail-on-alert: true
          github-token: ${{ secrets.GITHUB_TOKEN }}
          comment-on-alert: true
          alert-comment-cc-users: '@achimcc'
  
         